name: Local Aggregator Deploy
description: Runs an aggregator instance

runs:
  using: composite
  steps:
    - working-directory: ./
      shell: bash
      run: docker-compose up -d postgres

    - working-directory: ./aggregator
      shell: bash
      run: cp .env.local.example .env

    - working-directory: ./aggregator
      shell: bash
      run: deno run --allow-read --allow-env --allow-net ./programs/aggregator.ts &
