name: Locally Contract Deploy
description: Runs a Hardhat node & deploys contracts

runs:
  using: composite
  steps:
    - working-directory: ./
      run: docker-compose up -d postgres

    - working-directory: ./aggregator
      run: cp .env.local.example .env

    - working-directory: ./aggregator
      run: |
        deno run --allow-read --allow-env --allow-net ./programs/aggregator.ts &
      # wait 10 seconds to allow the aggregator to spin up
        sleep 10
