name: Locally Contract Deploy
description: Runs a Hardhat node & deploys contracts

runs:
  using: composite
  steps:
    - working-directory: ./
      shell: bash
      run: docker-compose up -d postgres

    - working-directory: ./aggregator
      shell: bash
      run: cp .env.local.example .env

    - working-directory: ./aggregator
      shell: bash
      run: ./programs/aggregator.ts &
