/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import {BytesLike} from "@ethersproject/bytes";
import {Listener, Provider} from "@ethersproject/providers";
import {FunctionFragment, EventFragment, Result} from "@ethersproject/abi";

interface SpokeRegistryInterface extends ethers.utils.Interface {
  functions: {
    "getSpokeAddress(uint256)": FunctionFragment;
    "numSpokes()": FunctionFragment;
    "registerSpoke(address)": FunctionFragment;
    "registeredSpokes(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getSpokeAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "numSpokes", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerSpoke",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredSpokes",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSpokeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "numSpokes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerSpoke",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredSpokes",
    data: BytesLike
  ): Result;

  events: {};
}

export class SpokeRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SpokeRegistryInterface;

  functions: {
    getSpokeAddress(
      spokeID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getSpokeAddress(uint256)"(
      spokeID: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    numSpokes(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "numSpokes()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    registerSpoke(
      spokeContract: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerSpoke(address)"(
      spokeContract: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registeredSpokes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "registeredSpokes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  getSpokeAddress(
    spokeID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "getSpokeAddress(uint256)"(
    spokeID: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  numSpokes(overrides?: CallOverrides): Promise<BigNumber>;

  "numSpokes()"(overrides?: CallOverrides): Promise<BigNumber>;

  registerSpoke(
    spokeContract: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerSpoke(address)"(
    spokeContract: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registeredSpokes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "registeredSpokes(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getSpokeAddress(
      spokeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getSpokeAddress(uint256)"(
      spokeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    numSpokes(overrides?: CallOverrides): Promise<BigNumber>;

    "numSpokes()"(overrides?: CallOverrides): Promise<BigNumber>;

    registerSpoke(
      spokeContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerSpoke(address)"(
      spokeContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registeredSpokes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "registeredSpokes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getSpokeAddress(
      spokeID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "getSpokeAddress(uint256)"(
      spokeID: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    numSpokes(overrides?: CallOverrides): Promise<BigNumber>;

    "numSpokes()"(overrides?: CallOverrides): Promise<BigNumber>;

    registerSpoke(
      spokeContract: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerSpoke(address)"(
      spokeContract: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registeredSpokes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "registeredSpokes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSpokeAddress(
      spokeID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getSpokeAddress(uint256)"(
      spokeID: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    numSpokes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "numSpokes()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerSpoke(
      spokeContract: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerSpoke(address)"(
      spokeContract: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registeredSpokes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "registeredSpokes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
