/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import {BytesLike} from "@ethersproject/bytes";
import {Listener, Provider} from "@ethersproject/providers";
import {FunctionFragment, EventFragment, Result} from "@ethersproject/abi";

interface TestCreate2TransferInterface extends ethers.utils.Interface {
  functions: {
    "_checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)": FunctionFragment;
    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)": FunctionFragment;
    "processCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])": FunctionFragment;
    "testProcessCreate2Transfer(bytes32,tuple,uint256,tuple,tuple)": FunctionFragment;
    "testProcessCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_checkSignature",
    values: [
      BigNumberish[],
      {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSignature",
    values: [
      BigNumberish[],
      {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "processCreate2TransferCommit",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "testProcessCreate2Transfer",
    values: [
      BytesLike,
      {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      BigNumberish,
      {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "testProcessCreate2TransferCommit",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "_checkSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processCreate2TransferCommit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testProcessCreate2Transfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testProcessCreate2TransferCommit",
    data: BytesLike
  ): Result;

  events: {};
}

export class TestCreate2Transfer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TestCreate2TransferInterface;

  functions: {
    _checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "_checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    processCreate2TransferCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: string;
      1: number;
    }>;

    "processCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: string;
      1: number;
    }>;

    testProcessCreate2Transfer(
      _balanceRoot: BytesLike,
      _tx: {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      tokenID: BigNumberish,
      from: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      to: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: number;
    }>;

    "testProcessCreate2Transfer(bytes32,tuple,uint256,tuple,tuple)"(
      _balanceRoot: BytesLike,
      _tx: {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      tokenID: BigNumberish,
      from: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      to: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: number;
    }>;

    testProcessCreate2TransferCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "testProcessCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  _checkSignature(
    signature: BigNumberish[],
    proof: {
      states: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      }[];
      stateWitnesses: BytesLike[][];
      pubkeysSender: BigNumberish[][];
      pubkeyWitnessesSender: BytesLike[][];
      pubkeysReceiver: BigNumberish[][];
      pubkeyWitnessesReceiver: BytesLike[][];
    },
    stateRoot: BytesLike,
    accountRoot: BytesLike,
    domain: BytesLike,
    txs: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "_checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
    signature: BigNumberish[],
    proof: {
      states: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      }[];
      stateWitnesses: BytesLike[][];
      pubkeysSender: BigNumberish[][];
      pubkeyWitnessesSender: BytesLike[][];
      pubkeysReceiver: BigNumberish[][];
      pubkeyWitnessesReceiver: BytesLike[][];
    },
    stateRoot: BytesLike,
    accountRoot: BytesLike,
    domain: BytesLike,
    txs: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkSignature(
    signature: BigNumberish[],
    proof: {
      states: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      }[];
      stateWitnesses: BytesLike[][];
      pubkeysSender: BigNumberish[][];
      pubkeyWitnessesSender: BytesLike[][];
      pubkeysReceiver: BigNumberish[][];
      pubkeyWitnessesReceiver: BytesLike[][];
    },
    stateRoot: BytesLike,
    accountRoot: BytesLike,
    domain: BytesLike,
    txs: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
    signature: BigNumberish[],
    proof: {
      states: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      }[];
      stateWitnesses: BytesLike[][];
      pubkeysSender: BigNumberish[][];
      pubkeyWitnessesSender: BytesLike[][];
      pubkeysReceiver: BigNumberish[][];
      pubkeyWitnessesReceiver: BytesLike[][];
    },
    stateRoot: BytesLike,
    accountRoot: BytesLike,
    domain: BytesLike,
    txs: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  processCreate2TransferCommit(
    stateRoot: BytesLike,
    maxTxSize: BigNumberish,
    feeReceiver: BigNumberish,
    txs: BytesLike,
    proofs: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    }[],
    overrides?: CallOverrides
  ): Promise<{
    result: number;
    0: string;
    1: number;
  }>;

  "processCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
    stateRoot: BytesLike,
    maxTxSize: BigNumberish,
    feeReceiver: BigNumberish,
    txs: BytesLike,
    proofs: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    }[],
    overrides?: CallOverrides
  ): Promise<{
    result: number;
    0: string;
    1: number;
  }>;

  testProcessCreate2Transfer(
    _balanceRoot: BytesLike,
    _tx: {
      fromIndex: BigNumberish;
      toIndex: BigNumberish;
      toPubkeyID: BigNumberish;
      amount: BigNumberish;
      fee: BigNumberish;
    },
    tokenID: BigNumberish,
    from: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    },
    to: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    },
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: number;
  }>;

  "testProcessCreate2Transfer(bytes32,tuple,uint256,tuple,tuple)"(
    _balanceRoot: BytesLike,
    _tx: {
      fromIndex: BigNumberish;
      toIndex: BigNumberish;
      toPubkeyID: BigNumberish;
      amount: BigNumberish;
      fee: BigNumberish;
    },
    tokenID: BigNumberish,
    from: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    },
    to: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    },
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: number;
  }>;

  testProcessCreate2TransferCommit(
    stateRoot: BytesLike,
    maxTxSize: BigNumberish,
    feeReceiver: BigNumberish,
    txs: BytesLike,
    proofs: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "testProcessCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
    stateRoot: BytesLike,
    maxTxSize: BigNumberish,
    feeReceiver: BigNumberish,
    txs: BytesLike,
    proofs: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    _checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: number;
    }>;

    "_checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: number;
    }>;

    checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    processCreate2TransferCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: string;
      1: number;
    }>;

    "processCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: string;
      1: number;
    }>;

    testProcessCreate2Transfer(
      _balanceRoot: BytesLike,
      _tx: {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      tokenID: BigNumberish,
      from: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      to: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: number;
    }>;

    "testProcessCreate2Transfer(bytes32,tuple,uint256,tuple,tuple)"(
      _balanceRoot: BytesLike,
      _tx: {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      tokenID: BigNumberish,
      from: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      to: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: number;
    }>;

    testProcessCreate2TransferCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: BigNumber;
    }>;

    "testProcessCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: BigNumber;
    }>;
  };

  filters: {};

  estimateGas: {
    _checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "_checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    processCreate2TransferCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "processCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testProcessCreate2Transfer(
      _balanceRoot: BytesLike,
      _tx: {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      tokenID: BigNumberish,
      from: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      to: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "testProcessCreate2Transfer(bytes32,tuple,uint256,tuple,tuple)"(
      _balanceRoot: BytesLike,
      _tx: {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      tokenID: BigNumberish,
      from: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      to: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testProcessCreate2TransferCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "testProcessCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "_checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeysSender: BigNumberish[][];
        pubkeyWitnessesSender: BytesLike[][];
        pubkeysReceiver: BigNumberish[][];
        pubkeyWitnessesReceiver: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    processCreate2TransferCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "processCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testProcessCreate2Transfer(
      _balanceRoot: BytesLike,
      _tx: {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      tokenID: BigNumberish,
      from: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      to: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "testProcessCreate2Transfer(bytes32,tuple,uint256,tuple,tuple)"(
      _balanceRoot: BytesLike,
      _tx: {
        fromIndex: BigNumberish;
        toIndex: BigNumberish;
        toPubkeyID: BigNumberish;
        amount: BigNumberish;
        fee: BigNumberish;
      },
      tokenID: BigNumberish,
      from: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      to: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testProcessCreate2TransferCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "testProcessCreate2TransferCommit(bytes32,uint256,uint256,bytes,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      feeReceiver: BigNumberish,
      txs: BytesLike,
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
