name: save artifacts
description: saves logs to artifact

runs:
  using: composite
  steps:
  - uses: actions/checkout@v2

  - run: mkdir -p artifacts/aggregator

  - run: echo test > artifacts/aggregator/aggLogs.txt

  - uses: actions/upload-artifact@v3
    with:
      name: aggregator-logs
      path: artifacts/aggregator/aggLogs.txt