name: Locally Contract Deploy
description: Runs a Hardhat node & deploys contracts

runs:
  using: composite
  steps:
    - working-directory: ./contracts
      run: yarn hardhat node &
    - working-directory: ./contracts
      run: yarn hardhat fundDeployer --network gethDev
    - working-directory: ./contracts
      run: yarn hardhat run scripts/deploy_all.ts --network gethDev