/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides
} from "@ethersproject/contracts";
import {BytesLike} from "@ethersproject/bytes";
import {Listener, Provider} from "@ethersproject/providers";
import {FunctionFragment, EventFragment, Result} from "@ethersproject/abi";

interface MassMigrationInterface extends ethers.utils.Interface {
  functions: {
    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,uint256,bytes)": FunctionFragment;
    "processMassMigrationCommit(bytes32,uint256,tuple,tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkSignature",
    values: [
      BigNumberish[],
      {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "processMassMigrationCommit",
    values: [
      BytesLike,
      BigNumberish,
      {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processMassMigrationCommit",
    data: BytesLike
  ): Result;

  events: {};
}

export class MassMigration extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MassMigrationInterface;

  functions: {
    checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      spokeID: BigNumberish,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,uint256,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      spokeID: BigNumberish,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    processMassMigrationCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      committed: {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: string;
      1: number;
    }>;

    "processMassMigrationCommit(bytes32,uint256,tuple,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      committed: {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: string;
      1: number;
    }>;
  };

  checkSignature(
    signature: BigNumberish[],
    proof: {
      states: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      }[];
      stateWitnesses: BytesLike[][];
      pubkeys: BigNumberish[][];
      pubkeyWitnesses: BytesLike[][];
    },
    stateRoot: BytesLike,
    accountRoot: BytesLike,
    domain: BytesLike,
    spokeID: BigNumberish,
    txs: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,uint256,bytes)"(
    signature: BigNumberish[],
    proof: {
      states: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      }[];
      stateWitnesses: BytesLike[][];
      pubkeys: BigNumberish[][];
      pubkeyWitnesses: BytesLike[][];
    },
    stateRoot: BytesLike,
    accountRoot: BytesLike,
    domain: BytesLike,
    spokeID: BigNumberish,
    txs: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  processMassMigrationCommit(
    stateRoot: BytesLike,
    maxTxSize: BigNumberish,
    committed: {
      accountRoot: BytesLike;
      signature: BigNumberish[];
      spokeID: BigNumberish;
      withdrawRoot: BytesLike;
      tokenID: BigNumberish;
      amount: BigNumberish;
      feeReceiver: BigNumberish;
      txs: BytesLike;
    },
    proofs: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    }[],
    overrides?: CallOverrides
  ): Promise<{
    result: number;
    0: string;
    1: number;
  }>;

  "processMassMigrationCommit(bytes32,uint256,tuple,tuple[])"(
    stateRoot: BytesLike,
    maxTxSize: BigNumberish,
    committed: {
      accountRoot: BytesLike;
      signature: BigNumberish[];
      spokeID: BigNumberish;
      withdrawRoot: BytesLike;
      tokenID: BigNumberish;
      amount: BigNumberish;
      feeReceiver: BigNumberish;
      txs: BytesLike;
    },
    proofs: {
      state: {
        pubkeyID: BigNumberish;
        tokenID: BigNumberish;
        balance: BigNumberish;
        nonce: BigNumberish;
      };
      witness: BytesLike[];
    }[],
    overrides?: CallOverrides
  ): Promise<{
    result: number;
    0: string;
    1: number;
  }>;

  callStatic: {
    checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      spokeID: BigNumberish,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,uint256,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      spokeID: BigNumberish,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    processMassMigrationCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      committed: {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: string;
      1: number;
    }>;

    "processMassMigrationCommit(bytes32,uint256,tuple,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      committed: {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<{
      result: number;
      0: string;
      1: number;
    }>;
  };

  filters: {};

  estimateGas: {
    checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      spokeID: BigNumberish,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,uint256,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      spokeID: BigNumberish,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    processMassMigrationCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      committed: {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "processMassMigrationCommit(bytes32,uint256,tuple,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      committed: {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkSignature(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      spokeID: BigNumberish,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkSignature(uint256[2],tuple,bytes32,bytes32,bytes32,uint256,bytes)"(
      signature: BigNumberish[],
      proof: {
        states: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        }[];
        stateWitnesses: BytesLike[][];
        pubkeys: BigNumberish[][];
        pubkeyWitnesses: BytesLike[][];
      },
      stateRoot: BytesLike,
      accountRoot: BytesLike,
      domain: BytesLike,
      spokeID: BigNumberish,
      txs: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    processMassMigrationCommit(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      committed: {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "processMassMigrationCommit(bytes32,uint256,tuple,tuple[])"(
      stateRoot: BytesLike,
      maxTxSize: BigNumberish,
      committed: {
        accountRoot: BytesLike;
        signature: BigNumberish[];
        spokeID: BigNumberish;
        withdrawRoot: BytesLike;
        tokenID: BigNumberish;
        amount: BigNumberish;
        feeReceiver: BigNumberish;
        txs: BytesLike;
      },
      proofs: {
        state: {
          pubkeyID: BigNumberish;
          tokenID: BigNumberish;
          balance: BigNumberish;
          nonce: BigNumberish;
        };
        witness: BytesLike[];
      }[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
