name: extension-release

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./extension

env:
  NODEJS_VERSION: 16.x

jobs:
  chrome:
    runs-on: ubuntu-latest
    environment: extension-release

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build-upload-extension
      with:
        node-version: ${{ env.NODEJS_VERSION }}
        browser: chrome
        file-name: chrome.zip
        tag-name: ${{ github.ref }}

  firefox:
    runs-on: ubuntu-latest
    environment: extension-release

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build-upload-extension
      with:
        node-version: ${{ env.NODEJS_VERSION }}
        browser: firefox
        file-name: firefox.xpi
        tag-name: ${{ github.ref }}

  opera:
    runs-on: ubuntu-latest
    environment: extension-release

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build-upload-extension
      with:
        node-version: ${{ env.NODEJS_VERSION }}
        browser: opera
        file-name: opera.crx
        tag-name: ${{ github.ref }}
